FROM ruby:2.7

# Set default locale for the environment
ENV LC_ALL C.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8

WORKDIR /usr/src/app

COPY Gemfile Gemfile.lock jekyll-text-theme.gemspec ./
RUN gem install bundler:1.17.3
RUN bundle install

EXPOSE 4000

CMD ["bundle", "exec", "jekyll", "help"]
